"""Initial migration.

Revision ID: 78befe9b99d2
Revises: 
Create Date: 2023-09-26 10:45:15.588245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78befe9b99d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_list')
    # ### end Alembic commands ###
